<a href="https://www.kaggle.com/code/manavmaheshsanger/pandas-tutorial?scriptVersionId=184880731" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Pandas Walkthrough with DSMP

### Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of Python programming language.

# Pandas Series
A pandas series is like a column in a table. It is a 1D array holding data of any type. For ex. in the student table, series could be name, marks, rollno, etc.

In [1]:
# importing pandas
import pandas as pd
import numpy as np

In [ ]:
# Creating a series from a list of strings
country = ["India", "Pakistan", "USA", "China", "Nepal", "Bhutan", "Sri Lanka", "Tibet", "Bangladesh"]
s1 = pd.Series(country)
print(s1)

In [ ]:
# Creating a series from a list of integers
runs = [12,54,23,78,43,59,26,59,26,15,58,36,53]
s2 = pd.Series(runs)
print(s2)

In [ ]:
# Custom indexing
marks = [95, 23, 99, 85]
subjects = ["Mathematics", "Public Speaking", "Computer Science", "Physics"]
s3 = pd.Series(marks, index=subjects)
print(s3)

In [ ]:
# Giving a name to the series
s3 = pd.Series(marks, index=subjects, name="Manav's Marks")
print(s3)

In [ ]:
# Series from a dictionary
marks = {
    "Mathematics" : 95,
    "Public Speaking" : 23,
    "Computer Science" : 99,
    "Physics" : 85,
}
marks_series = pd.Series(marks, name="Manav's Marks")
print(marks_series)

# Series Attributes

In [ ]:
# size
marks_series.size

In [ ]:
#dtype
marks_series.dtype

In [ ]:
# name
marks_series.name

In [ ]:
# is_unique : returns false if a value repeats in the series
print(marks_series.is_unique)
print(pd.Series([1,2,3,4,1,3]).is_unique)

In [ ]:
# index
print(marks_series.index)
print(s2.index)

In [ ]:
# values
print(marks_series.values)
print(s2.values)

# Series using read_csv

In [ ]:
# data with 1 col
# to get data path, go to datasets section on the right, add dataset-for-pandas-series if not added, then right click on the required csv file and copy path
a = pd.read_csv("/kaggle/input/dataset-for-pandas-series/subs.csv")
print(type(a))
b = pd.read_csv("/kaggle/input/dataset-for-pandas-series/subs.csv").squeeze()
print(type(b))
print(b)

In [ ]:
# data with 2 cols
vk = pd.read_csv("/kaggle/input/dataset-for-pandas-series/kohli_ipl.csv", index_col="match_no").squeeze()
print(vk, "\n\n")

bwood = pd.read_csv("/kaggle/input/dataset-for-pandas-series/bollywood.csv", index_col="movie").squeeze()
print(bwood)

# Series methods

In [ ]:
# head and tail
print(vk.head()) # gives the first 5 data points
print(vk.tail()) # gives the last 5 data points

print(vk.head(10)) # gives n data points

In [ ]:
# sample : gives a random row
print(bwood.sample(), "\n\n")

print(bwood.sample(5))

In [ ]:
# value_counts : give the frequency of each value in the series
print(bwood.value_counts())

In [ ]:
# sort_values : sorts values
# print(vk.sort_values())
print(vk.sort_values(ascending=False), "\n") # changes are not permanent
# vk.sort_values(ascending=False, inplace = True) # changes are permanent, vk series is changed

# returning a numpy array with the highest score of Virat Kohli
print(vk.sort_values(ascending=False).head(1).values[0])

In [ ]:
# sort index : similar to sort values but for indices, also has inplace method
print(bwood.sort_index(ascending=False), "\n") # changes are not permanent

# Mathematical methods on series

In [ ]:
# count() : returns the total count of values excluding null values
# size : returns the total count of values including null values
print(vk.count())
print(vk.size)

In [ ]:
# sum(), product()
print(vk.sum())
# print(bwood.sum()) # concatenates all strings
# print(vk.sum(5)) # not allowed

In [ ]:
# mean, median, mode, std, var
print(vk.mean())
print(vk.median())
print(vk.mode())
print(vk.std())
print(vk.var())

In [ ]:
# min(), max()
print(vk.min())
print(vk.max())

In [ ]:
# describe()
print(vk.describe())

# Series indexing

In [ ]:
# integer indexing
x = pd.Series([1,3,4,5,6,7,8,9,52,234,56,34])
print(x[1])

In [ ]:
# negative indexing WORKS in integer string series
print(bwood[-1])
# negative indexing DOESN'T WORKS in integer indexed series
print(x[-1])

In [ ]:
# when the keys are strings, they can also be integer indexed
print(bwood[0])
print(bwood["Battalion 609"])
print("\n",bwood)

In [ ]:
# slicing
print(vk[5:16])

# negative slicing works here with integer indexed series
print(vk[-5:])

In [ ]:
# fancy indexing (exactly like numpy) , also works with string indexed series
print(vk[[1,3,4,9]])

# Editing Series

In [ ]:
# using indexing
# vk[1] = 400

#what if index doesn't exists : new index is created

vk[4:6] = [100,100]
vk[[1,4,7]] = [100,100,100]

# Python functionalities in Series

In [ ]:
# len
print(len(vk))

#type
print(type(vk))

#sorted
print(sorted(vk)) # note : output is a list

# min and max
print(min(vk), max(vk))

In [ ]:
# type conversion
print(list(vk))
print("\n\n")
print(dict(vk))

In [ ]:
# membership operator 
print(100 in vk) # Note : searches for index, not value
print(250 in vk) 

print(100 in vk) # Note : searches in value
print(200 in vk)

In [ ]:
# looping
num = 0
for i in vk.index: 
    num+=1
for i in vk.values:
    num+=1
    
print(num)

In [ ]:
#arithmetic operators
print(vk+100)

#relational operators
print(vk < 50)

# Boolean indexing on Series

In [ ]:
# Finding number of 50s and 100s scored by Virat Kohli
print(vk[vk>=50].size)
print(vk[vk>=100].size)

In [ ]:
# finding number of ducks
print(vk[vk == 0].size)

In [ ]:
# actors who did more than 20 movies
print(bwood.value_counts()[bwood.value_counts() > 20])

# Plotting graphs

In [ ]:
vk = pd.read_csv("/kaggle/input/dataset-for-pandas-series/kohli_ipl.csv", index_col="match_no").squeeze()
vk.plot()

In [ ]:
bwood.value_counts().head(20).plot(kind="bar")

# Creating a DataFrame

A dataframe is a collection of series. its rows are called series and its cols are also called series

In [4]:
# from lists
student_data = [[100, 80, 10],
               [90, 70, 7],
               [120, 100, 14],
               [80, 50, 2]
               ]

df1 = pd.DataFrame(student_data, columns=["iq", "marks", "package"])
print(df1)

    iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2

In [5]:
# using dicts
student_dict = {
    "iq" : [100, 90, 120, 80],
    "marks" : [80, 70, 100, 50],
    "package" : [10, 7, 14, 2],
}

df2 = pd.DataFrame(student_dict)
print(df2)

    iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2

In [2]:
# using read_csv
movies = pd.read_csv("/kaggle/input/dataset2/movies.csv")
print(movies)

                                   title_x     imdb_id  \
0                 Uri: The Surgical Strike   tt8291224
1                            Battalion 609   tt9472208
2     The Accidental Prime Minister (film)   tt6986710
3                          Why Cheat India   tt8108208
4                          Evening Shadows   tt6028796
...                                    ...         ...
1624                 Tera Mera Saath Rahen   tt0301250
1625                  Yeh Zindagi Ka Safar   tt0298607
1626                       Sabse Bada Sukh   tt0069204
1627                                 Daaka  tt10833860
1628                              Humsafar   tt2403201

                                            poster_path  \
0     https://upload.wikimedia.org/wikipedia/en/thum...
1                                                   NaN
2     https://upload.wikimedia.org/wikipedia/en/thum...
3     https://upload.wikimedia.org/wikipedia/en/thum...
4                                                   NaN
...                                                 ...
1624  https://upload.wikimedia.org/wikipedia/en/2/2b...
1625  https://upload.wikimedia.org/wikipedia/en/thum...
1626                                                NaN
1627  https://upload.wikimedia.org/wikipedia/en/thum...
1628  https://upload.wikimedia.org/wikipedia/en/thum...

                                              wiki_link  \
0     https://en.wikipedia.org/wiki/Uri:_The_Surgica...
1           https://en.wikipedia.org/wiki/Battalion_609
2     https://en.wikipedia.org/wiki/The_Accidental_P...
3         https://en.wikipedia.org/wiki/Why_Cheat_India
4         https://en.wikipedia.org/wiki/Evening_Shadows
...                                                 ...
1624  https://en.wikipedia.org/wiki/Tera_Mera_Saath_...
1625  https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...
1626      https://en.wikipedia.org/wiki/Sabse_Bada_Sukh
1627                https://en.wikipedia.org/wiki/Daaka
1628             https://en.wikipedia.org/wiki/Humsafar

                            title_y                 original_title  is_adult  \
0          Uri: The Surgical Strike       Uri: The Surgical Strike         0
1                     Battalion 609                  Battalion 609         0
2     The Accidental Prime Minister  The Accidental Prime Minister         0
3                   Why Cheat India                Why Cheat India         0
4                   Evening Shadows                Evening Shadows         0
...                             ...                            ...       ...
1624          Tera Mera Saath Rahen          Tera Mera Saath Rahen         0
1625           Yeh Zindagi Ka Safar           Yeh Zindagi Ka Safar         0
1626                Sabse Bada Sukh                Sabse Bada Sukh         0
1627                          Daaka                          Daaka         0
1628                       Humsafar                       Humsafar         0

      year_of_release runtime            genres  imdb_rating  imdb_votes  \
0                2019     138  Action|Drama|War          8.4       35112
1                2019     131               War          4.1          73
2                2019     112   Biography|Drama          6.1        5549
3                2019     121       Crime|Drama          6.0        1891
4                2018     102             Drama          7.3         280
...               ...     ...               ...          ...         ...
1624             2001     148             Drama          4.9         278
1625             2001     146             Drama          3.0         133
1626             2018      \N      Comedy|Drama          6.1          13
1627             2019     136            Action          7.4          38
1628             2011      35     Drama|Romance          9.0        2968

                                                  story  \
0     Divided over five chapters  the film chronicle...
1     The story revolves around a cricket match betw...
2     Based on the memoir by Indian policy analyst S...
3     The movie focuses on existing malpractices in ...
4     While gay rights and marriage equality has bee...
...                                                 ...
1624  Raj Dixit lives with his younger brother  Rahu...
1625  Hindi pop-star  Sarina Devan  lives a wealthy ...
1626  Village born Lalloo re-locates to Bombay  and ...
1627  Shinda tries robbing a bank so he can be wealt...
1628  Sara and Ashar are childhood friends who share...

                                                summary tagline  \
0     Indian army special forces execute a covert op...     NaN
1     The story of Battalion 609 revolves around a c...     NaN
2     Explores Manmohan Singh's tenure as the Prime ...     NaN
3     The movie focuses on existing malpractices in ...     NaN
4     Under the 'Evening Shadows'  truth often plays...     NaN
...                                                 ...     ...
1624  A man is torn between his handicapped brother ...     NaN
1625  A singer finds out she was adopted when the ed...     NaN
1626  Village born Lalloo re-locates to Bombay  and ...     NaN
1627  Shinda tries robbing a bank so he can be wealt...     NaN
1628  Ashar and Khirad are forced to get married due...     NaN

                                                 actors  \
0     Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
1     Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...
2     Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...
3     Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...
4     Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...
...                                                 ...
1624  Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...
1625  Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...
1626  Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...
1627                          Gippy Grewal|Zareen Khan|
1628                                        Fawad Khan|

            wins_nominations              release_date
0                     4 wins     11 January 2019 (USA)
1                        NaN   11 January 2019 (India)
2                        NaN     11 January 2019 (USA)
3                        NaN     18 January 2019 (USA)
4     17 wins & 1 nomination   11 January 2019 (India)
...                      ...                       ...
1624                     NaN   7 November 2001 (India)
1625                     NaN  16 November 2001 (India)
1626                     NaN                       NaN
1627                     NaN     1 November 2019 (USA)
1628                     NaN     TV Series (2011–2012)

[1629 rows x 18 columns]

In [3]:
ipl = pd.read_csv("/kaggle/input/dataset2/ipl-matches.csv")
print(ipl)

          ID        City        Date   Season  MatchNumber  \
0    1312200   Ahmedabad  2022-05-29     2022        Final
1    1312199   Ahmedabad  2022-05-27     2022  Qualifier 2
2    1312198     Kolkata  2022-05-25     2022   Eliminator
3    1312197     Kolkata  2022-05-24     2022  Qualifier 1
4    1304116      Mumbai  2022-05-22     2022           70
..       ...         ...         ...      ...          ...
945   335986     Kolkata  2008-04-20  2007/08            4
946   335985      Mumbai  2008-04-20  2007/08            5
947   335984       Delhi  2008-04-19  2007/08            3
948   335983  Chandigarh  2008-04-19  2007/08            2
949   335982   Bangalore  2008-04-18  2007/08            1

                           Team1                        Team2  \
0               Rajasthan Royals               Gujarat Titans
1    Royal Challengers Bangalore             Rajasthan Royals
2    Royal Challengers Bangalore         Lucknow Super Giants
3               Rajasthan Royals               Gujarat Titans
4            Sunrisers Hyderabad                 Punjab Kings
..                           ...                          ...
945        Kolkata Knight Riders              Deccan Chargers
946               Mumbai Indians  Royal Challengers Bangalore
947             Delhi Daredevils             Rajasthan Royals
948              Kings XI Punjab          Chennai Super Kings
949  Royal Challengers Bangalore        Kolkata Knight Riders

                                          Venue                   TossWinner  \
0              Narendra Modi Stadium, Ahmedabad             Rajasthan Royals
1              Narendra Modi Stadium, Ahmedabad             Rajasthan Royals
2                         Eden Gardens, Kolkata         Lucknow Super Giants
3                         Eden Gardens, Kolkata               Gujarat Titans
4                      Wankhede Stadium, Mumbai          Sunrisers Hyderabad
..                                          ...                          ...
945                                Eden Gardens              Deccan Chargers
946                            Wankhede Stadium               Mumbai Indians
947                            Feroz Shah Kotla             Rajasthan Royals
948  Punjab Cricket Association Stadium, Mohali          Chennai Super Kings
949                       M Chinnaswamy Stadium  Royal Challengers Bangalore

    TossDecision SuperOver                  WinningTeam    WonBy  Margin  \
0            bat         N               Gujarat Titans  Wickets     7.0
1          field         N             Rajasthan Royals  Wickets     7.0
2          field         N  Royal Challengers Bangalore     Runs    14.0
3          field         N               Gujarat Titans  Wickets     7.0
4            bat         N                 Punjab Kings  Wickets     5.0
..           ...       ...                          ...      ...     ...
945          bat         N        Kolkata Knight Riders  Wickets     5.0
946          bat         N  Royal Challengers Bangalore  Wickets     5.0
947          bat         N             Delhi Daredevils  Wickets     9.0
948          bat         N          Chennai Super Kings     Runs    33.0
949        field         N        Kolkata Knight Riders     Runs   140.0

    method Player_of_Match                                       Team1Players  \
0      NaN       HH Pandya  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
1      NaN      JC Buttler  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...
2      NaN      RM Patidar  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...
3      NaN       DA Miller  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
4      NaN   Harpreet Brar  ['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...
..     ...             ...                                                ...
945    NaN       DJ Hussey  ['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...
946    NaN      MV Boucher  ['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...
947    NaN     MF Maharoof  ['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...
948    NaN      MEK Hussey  ['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...
949    NaN     BB McCullum  ['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...

                                          Team2Players        Umpire1  \
0    ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...    CB Gaffaney
1    ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...    CB Gaffaney
2    ['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...  J Madanagopal
3    ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...   BNJ Oxenford
4    ['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...   AK Chaudhary
..                                                 ...            ...
945  ['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...      BF Bowden
946  ['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...       SJ Davis
947  ['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...      Aleem Dar
948  ['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...      MR Benson
949  ['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...      Asad Rauf

            Umpire2
0       Nitin Menon
1       Nitin Menon
2          MA Gough
3         VK Sharma
4     NA Patwardhan
..              ...
945     K Hariharan
946       DJ Harper
947  GA Pratapkumar
948      SL Shastri
949     RE Koertzen

[950 rows x 20 columns]

# Dataframe attributes and methods

In [7]:
# shape
print(ipl.shape)
print(movies.shape)

(950, 20)
(1629, 18)

In [10]:
# dtypes
print(movies.dtypes)
print(ipl.dtypes)

# object means string

title_x              object
imdb_id              object
poster_path          object
wiki_link            object
title_y              object
original_title       object
is_adult              int64
year_of_release       int64
runtime              object
genres               object
imdb_rating         float64
imdb_votes            int64
story                object
summary              object
tagline              object
actors               object
wins_nominations     object
release_date         object
dtype: object
ID                   int64
City                object
Date                object
Season              object
MatchNumber         object
Team1               object
Team2               object
Venue               object
TossWinner          object
TossDecision        object
SuperOver           object
WinningTeam         object
WonBy               object
Margin             float64
method              object
Player_of_Match     object
Team1Players        object
Team2Players        object
Umpire1             object
Umpire2             object
dtype: object

In [11]:
# index
print(movies.index)
print(ipl.index)

RangeIndex(start=0, stop=1629, step=1)
RangeIndex(start=0, stop=950, step=1)

In [12]:
# columns
print(movies.columns)
print(ipl.columns)

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='object')
Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2'],
      dtype='object')

In [14]:
# values
print(ipl.values)

[[1312200 'Ahmedabad' '2022-05-29' ...
  "['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pandya', 'DA Miller', 'R Tewatia', 'Rashid Khan', 'R Sai Kishore', 'LH Ferguson', 'Yash Dayal', 'Mohammed Shami']"
  'CB Gaffaney' 'Nitin Menon']
 [1312199 'Ahmedabad' '2022-05-27' ...
  "['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D Padikkal', 'SO Hetmyer', 'R Parag', 'R Ashwin', 'TA Boult', 'YS Chahal', 'M Prasidh Krishna', 'OC McCoy']"
  'CB Gaffaney' 'Nitin Menon']
 [1312198 'Kolkata' '2022-05-25' ...
  "['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda', 'MP Stoinis', 'E Lewis', 'KH Pandya', 'PVD Chameera', 'Mohsin Khan', 'Avesh Khan', 'Ravi Bishnoi']"
  'J Madanagopal' 'MA Gough']
 ...
 [335984 'Delhi' '2008-04-19' ...
  "['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif', 'DS Lehmann', 'RA Jadeja', 'M Rawat', 'D Salunkhe', 'SK Warne', 'SK Trivedi', 'MM Patel']"
  'Aleem Dar' 'GA Pratapkumar']
 [335983 'Chandigarh' '2008-04-19' ...
  "['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dhoni', 'SK Raina', 'JDP Oram', 'S Badrinath', 'Joginder Sharma', 'P Amarnath', 'MS Gony', 'M Muralitharan']"
  'MR Benson' 'SL Shastri']
 [335982 'Bangalore' '2008-04-18' ...
  "['SC Ganguly', 'BB McCullum', 'RT Ponting', 'DJ Hussey', 'Mohammad Hafeez', 'LR Shukla', 'WP Saha', 'AB Agarkar', 'AB Dinda', 'M Kartik', 'I Sharma']"
  'Asad Rauf' 'RE Koertzen']]

In [15]:
# head and tail
# same as series

In [18]:
# sample
print(ipl.sample())

         ID    City        Date   Season MatchNumber           Team1  \
808  419132  Mumbai  2010-03-30  2009/10          27  Mumbai Indians

               Team2              Venue      TossWinner TossDecision  \
808  Kings XI Punjab  Brabourne Stadium  Mumbai Indians        field

    SuperOver     WinningTeam    WonBy  Margin method Player_of_Match  \
808         N  Mumbai Indians  Wickets     4.0    NaN      SL Malinga

                                          Team1Players  \
808  ['S Dhawan', 'SR Tendulkar', 'KA Pollard', 'SS...

                                          Team2Players      Umpire1  \
808  ['RS Bopara', 'SE Marsh', 'MS Bisla', 'DPMD Ja...  BR Doctrove

         Umpire2
808  SK Tarapore

In [20]:
# info
print(movies.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   object
 1   imdb_id           1629 non-null   object
 2   poster_path       1526 non-null   object
 3   wiki_link         1629 non-null   object
 4   title_y           1629 non-null   object
 5   original_title    1629 non-null   object
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   object
 9   genres            1629 non-null   object
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   object
 13  summary           1629 non-null   object
 14  tagline           557 non-null    object
 15  actors            1624 non-null   object
 16  wins_nominations  707 non-null    object
 17  release_date      1522 non-null   object
dtypes: float64(1), int64(3), object(14)
memory usage: 229.2+ KB
None

In [23]:
# describle
print(movies.describe())

       is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

In [27]:
# isnull : if the data has null values
print(movies.isnull().sum())

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

In [31]:
# duplicated : checks for duplicate row
print(movies.duplicated().sum())
print(ipl.duplicated().sum())

0
0

In [34]:
# rename : used to rename a column
student_dict = {
    "iq" : [100, 90, 120, 80],
    "marks" : [80, 70, 100, 50],
    "package" : [10, 7, 14, 2],
}

df2 = pd.DataFrame(student_dict)
print(df2)

df2.rename(columns={"marks" : "percent", "package" : "lpa"}, inplace=True)
print(df2)

    iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2
    iq  percent  lpa
0  100       80   10
1   90       70    7
2  120      100   14
3   80       50    2

# DataFrame Math methods

In [38]:
#sum
students = df2
print(students)
print(students.sum()) # applied on all cols
print(students.sum(axis=1)) # applied on all rows

    iq  percent  lpa
0  100       80   10
1   90       70    7
2  120      100   14
3   80       50    2
iq         390
percent    300
lpa         33
dtype: int64
0    190
1    167
2    234
3    132
dtype: int64

In [ ]:
# other functions : min, max, mean, median, mode, std, var
# all these functions work exactly like in series, they also have the axis parameter : axis = 1 : apply operation row wise

# selecting columns from a dataframe

In [40]:
# single column
print(movies["title_x"])

0                   Uri: The Surgical Strike
1                              Battalion 609
2       The Accidental Prime Minister (film)
3                            Why Cheat India
4                            Evening Shadows
                        ...
1624                   Tera Mera Saath Rahen
1625                    Yeh Zindagi Ka Safar
1626                         Sabse Bada Sukh
1627                                   Daaka
1628                                Humsafar
Name: title_x, Length: 1629, dtype: object

In [41]:
# multiple columns (using fancy indexing)
print(movies[["title_x", "actors", "year_of_release"]])

                                   title_x  \
0                 Uri: The Surgical Strike
1                            Battalion 609
2     The Accidental Prime Minister (film)
3                          Why Cheat India
4                          Evening Shadows
...                                    ...
1624                 Tera Mera Saath Rahen
1625                  Yeh Zindagi Ka Safar
1626                       Sabse Bada Sukh
1627                                 Daaka
1628                              Humsafar

                                                 actors  year_of_release
0     Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...             2019
1     Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...             2019
2     Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...             2019
3     Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...             2019
4     Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...             2018
...                                                 ...              ...
1624  Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...             2001
1625  Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...             2001
1626  Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...             2018
1627                          Gippy Grewal|Zareen Khan|             2019
1628                                        Fawad Khan|             2011

[1629 rows x 3 columns]

In [43]:
print(ipl[["Team1", "Team2", "WinningTeam"]])

                           Team1                        Team2  \
0               Rajasthan Royals               Gujarat Titans
1    Royal Challengers Bangalore             Rajasthan Royals
2    Royal Challengers Bangalore         Lucknow Super Giants
3               Rajasthan Royals               Gujarat Titans
4            Sunrisers Hyderabad                 Punjab Kings
..                           ...                          ...
945        Kolkata Knight Riders              Deccan Chargers
946               Mumbai Indians  Royal Challengers Bangalore
947             Delhi Daredevils             Rajasthan Royals
948              Kings XI Punjab          Chennai Super Kings
949  Royal Challengers Bangalore        Kolkata Knight Riders

                     WinningTeam
0                 Gujarat Titans
1               Rajasthan Royals
2    Royal Challengers Bangalore
3                 Gujarat Titans
4                   Punjab Kings
..                           ...
945        Kolkata Knight Riders
946  Royal Challengers Bangalore
947             Delhi Daredevils
948          Chennai Super Kings
949        Kolkata Knight Riders

[950 rows x 3 columns]

# selecting rows from a DataFrame

* **iloc**: searches using index positions
* **loc**: searches using index labels

In [50]:
student_dict = {
    "name" : ["manav", "bhatt", "abdus", "aditya"],
    "iq" : [100, 90, 120, 80],
    "marks" : [80, 70, 100, 50],
    "package" : [10, 7, 14, 2],
}
students = pd.DataFrame(student_dict)
students.set_index("name", inplace=True) # we will look at set index later
print(students)

         iq  marks  package
name
manav   100     80       10
bhatt    90     70        7
abdus   120    100       14
aditya   80     50        2

In [55]:
# fetching using iloc
print(type(movies.iloc[0])) 
print(movies.iloc[0], "\n\n") 

print(type(movies.iloc[0:5])) 
print(movies.iloc[0:5])

# we can also do fancy indexing
# print(movies.iloc[[5, 13, 43, 1]])

<class 'pandas.core.series.Series'>
title_x                                      Uri: The Surgical Strike
imdb_id                                                     tt8291224
poster_path         https://upload.wikimedia.org/wikipedia/en/thum...
wiki_link           https://en.wikipedia.org/wiki/Uri:_The_Surgica...
title_y                                      Uri: The Surgical Strike
original_title                               Uri: The Surgical Strike
is_adult                                                            0
year_of_release                                                  2019
runtime                                                           138
genres                                               Action|Drama|War
imdb_rating                                                       8.4
imdb_votes                                                      35112
story               Divided over five chapters  the film chronicle...
summary             Indian army special forces execute a covert op...
tagline                                                           NaN
actors              Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
wins_nominations                                               4 wins
release_date                                    11 January 2019 (USA)
Name: 0, dtype: object


<class 'pandas.core.frame.DataFrame'>
                                title_x    imdb_id  \
0              Uri: The Surgical Strike  tt8291224
1                         Battalion 609  tt9472208
2  The Accidental Prime Minister (film)  tt6986710
3                       Why Cheat India  tt8108208
4                       Evening Shadows  tt6028796

                                         poster_path  \
0  https://upload.wikimedia.org/wikipedia/en/thum...
1                                                NaN
2  https://upload.wikimedia.org/wikipedia/en/thum...
3  https://upload.wikimedia.org/wikipedia/en/thum...
4                                                NaN

                                           wiki_link  \
0  https://en.wikipedia.org/wiki/Uri:_The_Surgica...
1        https://en.wikipedia.org/wiki/Battalion_609
2  https://en.wikipedia.org/wiki/The_Accidental_P...
3      https://en.wikipedia.org/wiki/Why_Cheat_India
4      https://en.wikipedia.org/wiki/Evening_Shadows

                         title_y                 original_title  is_adult  \
0       Uri: The Surgical Strike       Uri: The Surgical Strike         0
1                  Battalion 609                  Battalion 609         0
2  The Accidental Prime Minister  The Accidental Prime Minister         0
3                Why Cheat India                Why Cheat India         0
4                Evening Shadows                Evening Shadows         0

   year_of_release runtime            genres  imdb_rating  imdb_votes  \
0             2019     138  Action|Drama|War          8.4       35112
1             2019     131               War          4.1          73
2             2019     112   Biography|Drama          6.1        5549
3             2019     121       Crime|Drama          6.0        1891
4             2018     102             Drama          7.3         280

                                               story  \
0  Divided over five chapters  the film chronicle...
1  The story revolves around a cricket match betw...
2  Based on the memoir by Indian policy analyst S...
3  The movie focuses on existing malpractices in ...
4  While gay rights and marriage equality has bee...

                                             summary tagline  \
0  Indian army special forces execute a covert op...     NaN
1  The story of Battalion 609 revolves around a c...     NaN
2  Explores Manmohan Singh's tenure as the Prime ...     NaN
3  The movie focuses on existing malpractices in ...     NaN
4  Under the 'Evening Shadows'  truth often plays...     NaN

                                              actors        wins_nominations  \
0  Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...                  4 wins
1  Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...                     NaN
2  Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...                     NaN
3  Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...                     NaN
4  Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...  17 wins & 1 nomination

              release_date
0    11 January 2019 (USA)
1  11 January 2019 (India)
2    11 January 2019 (USA)
3    18 January 2019 (USA)
4  11 January 2019 (India)

In [58]:
# fetching using loc
print(students.loc["manav"])
print(students.loc["manav" : "abdus"])
# we can also apply iloc on string indexed dataframes
print(students.iloc[0])

# we can use all the indexing methods that apply to iloc

iq         100
marks       80
package     10
Name: manav, dtype: int64
        iq  marks  package
name
manav  100     80       10
bhatt   90     70        7
abdus  120    100       14
iq         100
marks       80
package     10
Name: manav, dtype: int64

# selecting both - rows and columns from a DataFrame

In [59]:
print(movies.iloc[0:3, 0:3])

                                title_x    imdb_id  \
0              Uri: The Surgical Strike  tt8291224
1                         Battalion 609  tt9472208
2  The Accidental Prime Minister (film)  tt6986710

                                         poster_path
0  https://upload.wikimedia.org/wikipedia/en/thum...
1                                                NaN
2  https://upload.wikimedia.org/wikipedia/en/thum...

# Filtering a DataFrame

In [62]:
# Finding all ipl final winners
final_matches = ipl[ipl["MatchNumber"] == "Final"]
print(final_matches[["Season", "WinningTeam"]])

      Season            WinningTeam
0       2022         Gujarat Titans
74      2021    Chennai Super Kings
134  2020/21         Mumbai Indians
194     2019         Mumbai Indians
254     2018    Chennai Super Kings
314     2017         Mumbai Indians
373     2016    Sunrisers Hyderabad
433     2015         Mumbai Indians
492     2014  Kolkata Knight Riders
552     2013         Mumbai Indians
628     2012  Kolkata Knight Riders
702     2011    Chennai Super Kings
775  2009/10    Chennai Super Kings
835     2009        Deccan Chargers
892  2007/08       Rajasthan Royals

In [74]:
# How many super overs occured
print(ipl[ipl["SuperOver"] == "Y"]["SuperOver"].count())

14

In [85]:
# how many matches did csk win in kolkata
print(ipl[ (ipl["City"] == "Kolkata") & (ipl["WinningTeam"] == "Chennai Super Kings")]["WinningTeam"].count())
print(ipl[ (ipl["City"] == "Chennai") & (ipl["WinningTeam"] == "Kolkata Knight Riders")]["WinningTeam"].count())

5
3

In [107]:
# toss winner is match winner percentage
match_winner_toss_winner = ipl[ipl["TossWinner"] == ipl["WinningTeam"]].shape[0]
total_matches = ipl.shape[0]

per = (match_winner_toss_winner/total_matches)*100
print(per)

51.473684210526315